### PR TITLE
OSD-26236 leaver process member removal 

### PR DESCRIPTION
**Pull request by luis-falcon**
Running the boilerplate-update in order to refresh the OWNER_ALIAS files.

### What type of PR is this?
cleanup

### CODE REVIEW

**Comment by bmeng** [comment]
Image test failed with following image pull error

```
 Trying to pull quay.io/redhat-services-prod/openshift/boilerplate:image-v5.0.1...
Warning: Pull failed, retrying in 5s ...

**Comment by joshbranham** [comment]
> Image test failed with following image pull error
> 
> ```
>  Trying to pull quay.io/redhat-services-prod/openshift/boilerplate:image-v5.0.1...
> Warning: Pull failed, retrying in 5s ... 
> ```

Yeah Anthony pointed that out for @luis-falcon  to update boilerplate again to fix it.

**Pull request merged**
