### PR TITLE
update boilerplate to add dependabot management of base image

### PR DESCRIPTION
**Pull request by tonytheleg**
### What type of PR is this?
_(bug/feature/cleanup/documentation/test/refactor)_

feature/refactor

### What this PR does / why we need it?

Updates boilerplate to include new dependabot changes for Dockerfile image management. This will ensure we are using tagged versions of ubi images, and dependabot will handle updating the image through PR's to ensure we stay up to date. This effort was done to ensure CVE's are remediated by updating the image consistently and ensuring new builds consistently without holding for code changes to trigger the build process.

Currently this update is being added now because there are CVE's in the current image and FedRAMP requirements determine we need to remediate those withing specific timelines.

### Which Jira/Github issue(s) this PR fixes?

_Fixes #_

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [ ] Included documentation changes with PR

### CODE REVIEW

**Comment by mjlshen** [comment]
/lgtm
The most copacetic of boilerplate updates

**Comment by bmeng** [comment]
Hi @tonytheleg thanks for posting the PR. 
But some of the tests are failed, would you mind take a look?

**Comment by mjlshen** [comment]
/lgtm
Now it's really the most copacetic of boilerplate updates

**Comment by tonytheleg** [comment]
> Hi @tonytheleg thanks for posting the PR. But some of the tests are failed, would you mind take a look?

Should be good now thanks to @mrbarge 's help!

**Pull request merged**
