### PR TITLE
lowercase pdb field

### PR DESCRIPTION
**Pull request by dofinn**
### What type of PR is this?
cleanup

### What this PR does / why we need it?
Standardisation with rest of repo/project.

### Which Jira/Github issue(s) this PR fixes?
N/A

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [x] Ran `make generate` command locally to validate code changes
- [x] Included documentation changes with PR

### CODE REVIEW

**Comment by mrbarge** [comment]
We need to manage this carefully - we have clusters with UpgradeConfigs already on them that feature a capitalized PDB. I believe this change will result in those clusters now reading in a PDB Force Drain Timeout of 0 because it is expecting a lowercase "pdb" field in the JSON and won't find it, so it will leave the default of 0 when unmarshalling. I was able to verify this with a quick test.

**Comment by sedroche** [comment]
> We need to manage this carefully - we have clusters with UpgradeConfigs already on them that feature a capitalized PDB. I believe this change will result in those clusters now reading in a PDB Force Drain Timeout of 0 because it is expecting a lowercase "pdb" field in the JSON and won't find it, so it will leave the default of 0 when unmarshalling. I was able to verify this with a quick test.

Did you test with a replacement manifest?

**Comment by mrbarge** [comment]
> > We need to manage this carefully - we have clusters with UpgradeConfigs already on them that feature a capitalized PDB. I believe this change will result in those clusters now reading in a PDB Force Drain Timeout of 0 because it is expecting a lowercase "pdb" field in the JSON and won't find it, so it will leave the default of 0 when unmarshalling. I was able to verify this with a quick test.
> 
> Did you test with a replacement manifest?

No, I just ran the operator locally, so still using the existing one. Either way, I would like some testing first on existing clusters with previous versions of the operator/UC to ensure this isn't going to some trouble when promoted.

**Comment by sedroche** [comment]
> Either way, I would like some testing first on existing clusters that have been running previous versions of the operator/UC to ensure this isn't going to some trouble when promoted.

Agreed. fyi there is [a doc](https://github.com/openshift/managed-upgrade-operator/blob/master/docs/catalogsource.md) for creating manifests to test.

**Comment by mrbarge** [comment]
Gave this a test and it seemed to behave okay. My testing scenario was:

- Created cluster with current prod version of MUO.
- Synced an UpgradeConfig (with uppercase PDB) to the cluster via Hive. 
- Upgraded cluster.
- Deployed this branch of MUO. Update the CRD to the one in this branch.

At this point, I observed no validation failures or alerts, however, MUO reported a "0" for the PDB config value as anticipated.
I also observed that, at this point, the existing Hive syncset of the UpgradeConfig no longer continued to sync, because the CR was invalid (an uppercase PDB).

- I updated the Hive syncset to use a lowercase PDB. Syncing of the Syncset resumed.
- MUO reported "60" for the PDB config value.

Based on these tests I feel pretty confident a promotion of this won't hurt production, though, we do need to do a regeneration of our SyncSets shortly after promotion.

@dofinn @sedroche if you are satisfied with the findings above I will remove my hold and approve.

**Comment by sedroche** [comment]
I would like to test this by manifest replacement using OLM to be 100% sure but the rest of this seems fine

**Comment by mrbarge** [comment]
So I did a test via manifest replacement as per @sedroche suggestion.

- Created a cluster with a custom catalogsource running the master branch MUO.
- Created an upgradeconfig with `PDBForceDrainTimeout` (uppercase)
- Updated the CatalogSource to install a new version of MUO featuring this branch.

When I approved the InstallPlan, the installation **failed** because the existing `UpgradeConfig` did not have a lowercase `pdbForceDrainTimeout` field:

```
  - lastTransitionTime: "2020-09-21T01:14:22Z"                                                                                                                                                                         lastUpdateTime: "2020-09-21T01:14:22Z"                                                                                                                                                                         
    message: 'error validating existing CRs agains new CRD''s schema: upgradeconfigs.upgrade.managed.openshift.io:                                                                                                 
      error validating custom resource against new schema &apiextensions.CustomResourceValidation{OpenAPIV3Schema:(*apiextensions.JSONSchemaProps)(0xc0022301e0)}:                                                 
      [].spec.pdbForceDrainTimeout: Required value'                                                                                                                                                                
```

I then tried a second test, this time ensuring that the UpgradeConfig had both an upper and lowercase variant of the `PDBForceDrainTimeout` field prior to approving the InstallPlan to upgrade MUO. This time the upgrade completed successfully.

Therefore if we go ahead with this change we **must** ensure all clusters have received a new UpgradeConfig that contains an uppercase and lowercase version of the `PDBForceDrainTimeout` field first, or else the installation will fail.

**Comment by sedroche** [comment]
> Therefore if we go ahead with this change we **must** ensure all clusters have received a new UpgradeConfig that contains an uppercase and lowercase version of the `PDBForceDrainTimeout` field first, or else the installation will fail.

I presume it can just be lowercase? Can we sync this to when/if this lands? -> https://github.com/openshift/managed-upgrade-operator/pull/132#issuecomment-694529366

**Comment by mrbarge** [comment]
> > Therefore if we go ahead with this change we **must** ensure all clusters have received a new UpgradeConfig that contains an uppercase and lowercase version of the `PDBForceDrainTimeout` field first, or else the installation will fail.
> 
> I presume it can just be lowercase? Can we sync this to when/if this lands? -> [#132 (comment)](https://github.com/openshift/managed-upgrade-operator/pull/132#issuecomment-694529366)

You're right, if it just has a lowercase version, then the old version of MUO will still be fine, it'll just read a value of 0 until a version of MUO with this branch lands.

I'll drop my thinking about how we manage this from an operational perspective on Slack.

**Comment by mrbarge** [comment]
@dofinn can you please fix the merge conflict here - I will then give it another test with a custom catalogsource and make sure this is good to go live.

**Pull request closed without merging**
