### PR TITLE
Update boilerplate & update crd to v1

### PR DESCRIPTION
**Pull request by sam-nguyen7**
### What type of PR is this?
Feature

### What this PR does / why we need it?
Update boilerplate version from v1.0 to v2.1
Update crd version from v1beta1 to v1

### Which Jira/Github issue(s) this PR fixes?
https://issues.redhat.com/browse/OSD-7597

### Pre-checks (if applicable):
- [ ] Tested latest changes against a cluster
- [x] Ran `make generate` command locally to validate code changes
- [ ] Included documentation changes with PR

### CODE REVIEW

**Comment by 2uasimojo** [comment]
Need to hold these PRs pending boilerplate updates to handle CRD v1 in the appsre pipeline script for bundle generation.

**Comment by 2uasimojo** [comment]
Need to delete the [old CRD](https://github.com/openshift/managed-upgrade-operator/blob/8e163abb12a13b823bab9c3f76eca8f0a35380d2/deploy/crds/upgrade.managed.openshift.io_upgradeconfigs_crd.yaml) so it doesn't end up in the bundle accidentally.

Otherwise this lgtm.
- The boilerplate update is clean
- The new CRD installs cleanly and `oc explain` works.

**Comment by sam-nguyen7** [comment]
> Need to delete the [old CRD](https://github.com/openshift/managed-upgrade-operator/blob/8e163abb12a13b823bab9c3f76eca8f0a35380d2/deploy/crds/upgrade.managed.openshift.io_upgradeconfigs_crd.yaml) so it doesn't end up in the bundle accidentally.
> 
> Otherwise this lgtm.
> 
> * The boilerplate update is clean
> * The new CRD installs cleanly and `oc explain` works.

Updated PR to delete old CRD from operator

**Comment by mrbarge** [comment]
I've given this a fairly thorough test and it seems good to me, thanks @sam-nguyen7 . The MUO maintainers will have a sync tomorrow to discuss before we give the green light, but it seems fine.

**Comment by ravitri** [comment]
Overall, the changes seem fine but couple of changes required regarding controller-gen. Also, need more insight into [comment](https://issues.redhat.com/browse/SDE-1281?focusedCommentId=16446352&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16446352). Will keep this PR on hold temporarily and take it up in next week again till there's more clarity.

/hold

**Comment by sam-nguyen7** [comment]
@ravitri @mrbarge Checking in, are we all set to merge this?

**Comment by 2uasimojo** [comment]
> couple of changes required regarding controller-gen.

Are you talking about #263? Not needed (and not preferred), as noted therein.

> Also, need more insight into [comment](https://issues.redhat.com/browse/SDE-1281?focusedCommentId=16446352&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16446352).

This shouldn't stop you. Something (we still haven't figured out what) is wrapping the v1beta1 CRDs and making them look like v1 CRDs. That may or may not allow them to install on 4.9. They definitely still don't install cleanly ("structural schema") or respond properly to `oc explain`. This PR will address all of that.

**Comment by ravitri** [comment]
@sam-nguyen7 - Yes, seems good now. Yesterday checked few things.
@2uasimojo - 
> Are you talking about #263? Not needed (and not preferred), as noted therein.

Yup agreed. Would be better to have controller-gen/openapi-gen via boilerplate itself. @mrbarge and I talked of the usecases to have some of these tools for local dev too as part of tools.go but that's a separate discussion. This PR is not stuck on that.

>This shouldn't stop you. Something (we still haven't figured out what) is wrapping the v1beta1 CRDs and making them look like v1 CRDs. That may or may not allow them to install on 4.9. They definitely still don't install cleanly ("structural schema") or respond properly to oc explain. This PR will address all of that.

This is exactly what checked yesterday and figured it out with API server team that it's all expected behaviour so far (even the non-structured schema causing `oc explain` to fail in existing CRD v1 on clusters). Please refer to my comment in epic [SDE-1281](https://issues.redhat.com/browse/SDE-1281?focusedCommentId=16471347&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16471347) for details. Once this CRD v1 change is merged, the `oc explain` command should be able to work correctly since there is no explicit conversion from v1beta1 to v1 API to result in `preserveUnknownFields: true` like in existing CRD v1 on clusters. 

So far, it all seems good to me but would be worth reviewing the change in staging clusters in better details before promoting to production (just incase we can catch some unexpected behaviour). Am ok to unhold the PR from my end. 

/unhold

**Pull request merged**
