### PR TITLE
Boilerplate update with common appsre pipelines

### PR DESCRIPTION
**Pull request by 2uasimojo**
### What type of PR is this?
refactor

### What this PR does / why we need it?
Brings MUO up to currency with boilerplate, including common appsre pipeline scripts

See individual commits for details.

[OSD-6851](https://issues.redhat.com/browse/OSD-6851)

### CODE REVIEW

**Comment by mrbarge** [comment]
/hold
for managing promotions

**Comment by 2uasimojo** [comment]
/hold for me too

py3 doesn't exist on the jenkins server, so the appsre pipeline will fail as written. We're working on getting a py3 container image we can use to invoke the bundle generator.

**Comment by 2uasimojo** [comment]
Ready for review. Leaving hold so we can manage merge timing.

**Comment by 2uasimojo** [comment]
/retest

oomkill

**Comment by 2uasimojo** [comment]
/retest

oomkill

**Comment by 2uasimojo** [comment]
/retest

oomkill

**Comment by mrbarge** [comment]
Everything looks fine to me, thanks for doing this. 

One minor nit before I sign off: the `manifests` make target in the operator's `Makefile` can now be removed as it is now referencing a script (`generate-local-operator-bundle.sh`) that has been removed in this PR.

**Comment by 2uasimojo** [comment]
> One minor nit before I sign off: the `manifests` make target in the operator's `Makefile` can now be removed as it is now referencing a script (`generate-local-operator-bundle.sh`) that has been removed in this PR.

Done.

**Comment by 2uasimojo** [comment]
/hold cancel

Let's do this.

**Pull request merged**
