### PR TITLE
Upgrade CRD version to v1 and operator-sdk version to 0.18.2

### PR DESCRIPTION
**Pull request by ravitri**
### What type of PR is this?
_(feature/documentation/refactor)_

### What this PR does / why we need it?
This PR has two major changes:
1. CRD version is upgraded from v1beta1 to v1
2. operator-sdk version upgraded from 0.17.0 to 0.18.2

### Which Jira/Github issue(s) this PR fixes?
_Fixes #_ https://issues.redhat.com/browse/OSD-5363

### Special notes for your reviewer:
1. Makefile has explicit mention of CRD version v1 in `operator-sdk generate crds --crd-version v1`
2. Documentation for local development updated and removed deprecated flags `--local` and `--watch-namespace`
3. Core gomod deps for operator-sdk 0.18 referred from https://deploy-preview-3543--operator-sdk.netlify.app/docs/upgrading-sdk-version/v0.18.0/ but it was incomplete and several other manual changes were to be done. I'll suggest some more changes in upstream too soon.
4. I checked `hack/generate-operator-bundle.py` file for CRD version schema changes too and seemed fine. If CI faces any failure then I'll fix that.
5. Now that CRD version v1 is enabled, end users can also run `oc explain` command against the custom resource and get more help. An example of it has been added in the FAQ doc for reference.

### Pre-checks (if applicable):
- [X] Tested latest changes against a cluster
- [X] Ran `make generate` command locally to validate code changes
- [X] Included documentation changes with PR
- [X] Clean run for `go mod tidy`

### CODE REVIEW

**Comment by ravitri** [comment]
/hold
Will wait for all OSD clusters to be on atleast 4.5 after which this PR can be merged

**Comment by mrbarge** [comment]
Gave this a test today.. built a replacement `catalogsource` from this branch that would upgrade the deployed operator with a MUO similarly built from this branch. I had some issues post-install of the newer `clusterserviceversion` because it didn't re-install the service account when upgrading the operator. Very similar to that observed in OSD-5749. Deleting the CSV/subscription and letting it re-install from scratch worked.

An upgrade using the operator from this branch worked.

At this stage I am reasonably confident about this with the exception of the issue of OSD-5749 which seemed to manifest itself here. I suspect after more investigation of OSD-5749 we'll know what's going on there. I'd like to give it at least one more test before we push it through though.

**Comment by 2uasimojo** [comment]
Working through some boilerplate onboarding uncovered more issues around CRD v1. We [discussed at length](https://coreos.slack.com/archives/CFJD1NZFT/p1605714226186200) and decided to freeze all our projects at CRD v1beta1 for the time being. This will be enforced via https://github.com/openshift/boilerplate/pull/98. That being the case, let's back the v1 cutover out of this PR. Sorry @ravitri! I know this is a reversal of what we discussed :(

**Comment by ravitri** [comment]
/close 
The upgrade to CRD version v1 would be managed by Boilerplate team for all operators so closing this PR for now.

**Pull request closed without merging**
