### PR TITLE
OSD-6525 Metric Crashloops

### PR DESCRIPTION
**Pull request by dofinn**
### What type of PR is this?
bug/feature

### What this PR does / why we need it? 

This PR enables MUO to tolerate a broken API and continue to start up.

```
{"level":"info","ts":1613702576.7495096,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1613702604.9765215,"logger":"cmd","msg":"Could not generate and serve custom resource metrics","error":"discovering resource information failed for UpgradeConfig in upgrade.managed.openshift.io/v1alpha1: unable to retrieve the complete list of server APIs: webhook.certmanager.k8s.io/v1beta1: the server is currently unable to handle the request"}
{"level":"error","ts":1613702604.9765632,"logger":"cmd","msg":"Metrics service is not added.","error":"discovering resource information failed for UpgradeConfig in upgrade.managed.openshift.io/v1alpha1: unable to retrieve the complete list of server APIs: webhook.certmanager.k8s.io/v1beta1: the server is currently unable to handle the request","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\t/workdir/cmd/manager/main.go:165\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
```

It does so by ripping out the metrics start up pieces from the
operator-sdk. Currently the sdk `Lists` all APIs and returns an error on
borken ones. Hence the above logs.

This PR moves that logic into the main.go so we can manipulate as
please. A refactor card will be created to follow this PR up.

How to replicate:

Create a broken apiservice

```
$ curl
https://raw.githubusercontent.com/dofinn/crs/main/api/apiservices/broken/apiservice.yaml
| oc --as backplane-cluster-admin create -f
```

Validate its broken

```
$ oc  api-resources | grep cert
certificatesigningrequests            csr                                certificates.k8s.io/v1                          false        CertificateSigningRequest
certmanagers                                                             operator.cert-manager.io/v1alpha1               true         CertManager
error: unable to retrieve the complete list of server APIs: webhook.certmanager.k8s.io/v1beta1: the server is currently unable to handle the request
```

Run MUO

It now handles this without performing a list of all apiservers and
matching the target api-resources based on GVK.

### Which Jira/Github issue(s) this PR fixes?

[OSD-6525](https://issues.redhat.com/browse/OSD-6525)

### Pre-checks (if applicable):
- [x] Tested latest changes against a cluster
- [ ] Ran `make generate` command locally to validate code changes
- [ ] Included documentation changes with PR

### CODE REVIEW

**Comment by T0MASD** [comment]
I was able to verify lint, tests and build the container locally using `boilerplate/_lib/container-make` 
There seems to be an issue with CI

**Comment by dofinn** [comment]
in favour of https://github.com/openshift/managed-upgrade-operator/pull/251

**Pull request closed without merging**
