### PR TITLE
Improve PR check

### PR DESCRIPTION
**Pull request by ravitri**
Add checks to app-sre PR script to run `make generate` and `make lint` for every PR that is raised. It should fail if any local changes found after `make generate` command. `golangci-lint cache clean` is added for local run of `make lint` command failures.

### CODE REVIEW

**Comment by 2uasimojo** [comment]
It looks like the regenerated file results in a circular import. That's certainly damage from a different PR, and should arguably be fixed in a different PR, but this will need to be respun either way.

Leaving my approval, since this is doing the right thing, and won't merge until CI passes anyway. (Not to mention that I'm not an approver in this repo, so my lgtm doesn't mean much :P )

**Comment by sedroche** [comment]
Can we add a gofmt check too? `gofmt -l ./pkg/ util/` maybe?

**Comment by ravitri** [comment]
/close
To be handled as part of the boilerplate project's standardization

**Pull request closed without merging**
