### PR TITLE
OSD-24722: Adding unit test case

### PR DESCRIPTION
**Pull request by TheUndeadKing**
### What type of PR is this?
test

### What this PR does / why we need it?
Adding unit test for func inside `/pkg/notifier`

### Which Jira/Github issue(s) this PR fixes?
[OSD-24722](https://issues.redhat.com/browse/OSD-24722)

### CODE REVIEW

**Comment by TheUndeadKing** [comment]
Screenshot 2024-07-29 at 3 00 55 PM/assets/ef30d0e9-2255-45c2-98b2-4267c3c8ba6f">
Screenshot 2024-07-29 at 3 01 42 PM

**Comment by TheUndeadKing** [comment]
Screenshot 2024-07-29 at 3 00 55 PM
Screenshot 2024-07-29 at 3 01 42 PM
Screenshot 2024-07-29 at 3 02 21 PM

**Comment by ravitri** [comment]
/approve

Thanks a lot Anwar for the PR and Shital and Tony for the review :+1:

**Comment by ravitri** [comment]
/approve
/lgtm

Thanks a lot Anwar for the PR and Shital and Tony for the review 👍

**Pull request merged**
