### PR TITLE
OSD-15609 go1.19 and k8s dependency bump

### PR DESCRIPTION
**Pull request by a7vicky**
### What type of PR is this?
_cleanup_

### What this PR does / why we need it?
The general dependency bump 
-  `go` to **1.19**
-  `k8s api`  to **v0.26.3**
-  `controller-runtime` to **v0.14.5**

### Which Jira/Github issue(s) this PR fixes?

_Fixes #_ [OSD-15609](https://issues.redhat.com/browse/OSD-15609)

### Pre-checks (if applicable):
- [x] Tested latest changes against a cluster
- [ ] Included documentation changes with PR

### CODE REVIEW

**Comment by a7vicky** [comment]
/hold
Testing TBD

**Comment by a7vicky** [comment]
/unhold
Successfully upgraded stage cluster from 
-  4.10.53  ->  4.11.33
-  4.11.33  ->  4.12.7

**Comment by ravitri** [comment]
@a7vicky - Overall LGTM but could you also add documentation changes regarding updated version of tools etc for development/testing?

**Pull request merged**
