### PR TITLE
Sdcicd 1052 osde2e test harness

### PR DESCRIPTION
**Pull request by ritmun**
This PR is reopened, should be merged pending the issue resolution here https://redhat-internal.slack.com/archives/CCX9DB894/p1689023965750439?thread_ts=1688989370.970789&cid=CCX9DB894 

### What type of PR is this?
e2e testing

### What this PR does / why we need it?
1. Adds osde2e bp convention
2. creates a e2e test harness within MUO repo. 

The test harness contains e2e tests currently running within osde2e framework. Please review the PR to ensure it looks good and no harm is done to the operator.
Please note that this is just the first phase of decentralizing your e2e testing. 

### Which Jira/Github issue(s) this PR fixes?
[SDCICD-1052](https://issues.redhat.com//browse/SDCICD-1052)
 

### Special notes for your reviewer:
We’ll continue to run the existing tests within osde2e, and are NOT changing the osde2e pipeline to run this yet. That will be planned in Q3. With that said, any new e2e tests for MUO should **not** be added to the osde2e repo after this merge, since this harness will be the new location for the e2e tests.

Based on my thread here, I've removed the spec for UC with past start date https://redhat-internal.slack.com/archives/CFJD1NZFT/p1688076884075809 

 
To test this harness locally, comment suiteConfig, reporterConfig from osde2e/managed_upgrade_operator_runner_test.go  and run `KUBECONFIG=(your kubeadm config) OCM_ENVIRONMENT=stage ginkgo run --tags osde2e ./osde2e/ -v`

### Pre-checks (if applicable):
- [x] Tested latest changes against a cluster
- [ ] Included documentation changes with PR

### Post checks
app-interface PR to add harness image publishing to operator build
followup task: MErge this PR  https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/72934

### CODE REVIEW

**Comment by mrbarge** [comment]
Just putting a hold on until we know more about why this had problems last time.
Refs OSD-17455
/hold

**Comment by shitaljante** [comment]
Created a [PR](https://github.com/ritmun/managed-upgrade-operator/pull/1) to address the upgrade not starting issue.

**Comment by ravitri** [comment]
/unhold
/approve

Based on @shitaljante's findings in https://issues.redhat.com//browse/OSD-17455, the issue was found and fix is added in this PR. We can see how the upgrades go in e2e tests. Thank you Shital!

**Pull request merged**
