### PR TITLE
Add operator-sdk 0.18.2 and controller-runtime 0.8.3 changes

### PR DESCRIPTION
**Pull request by ravitri**
### What type of PR is this?
_(cleanup/refactor)_

### What this PR does / why we need it?
This PR is about upgrading the dependencies of MUO to the highest version of operator-sdk that is supported by Boilerplate (0.18.2). Also, the controller-runtime dependency is updated to 0.8.3. 

### Which Jira/Github issue(s) this PR fixes?
_Fixes #_ [OSD-6223](https://issues.redhat.com/browse/OSD-6223)

### Special notes for your reviewer:
1. Operator-sdk version - 0.18.2
2. Controller-runtime version - 0.8.3

### Pre-checks (if applicable):
- [x] Tested latest changes against a cluster
- [x] Ran `make generate` command locally to validate code changes
- [ ] Included documentation changes with PR

### CODE REVIEW

**Comment by ravitri** [comment]
/hold
Tested changes and upgraded cluster. Works fine so far. However, `make test` has lot of failures which am still checking. Will add that change in separate commit soon.

**Comment by ravitri** [comment]
PR #233 is already open to update the boilerplate stack with Go 1.16. That would address some of the failures. The other failures regard lint which is yet to be addressed. Working on it.

**Comment by ravitri** [comment]
/unhold
Ok to review/test after updating boilerplate image to 1.0.0. No additional changes done and previous failures passed after boiler plate change.

**Comment by mrbarge** [comment]
Have successfully tested this on:
- 4.5.11 to 4.5.16
- 4.6.17 to 4.6.29
Also confirmed that PDB drain logic is still working correctly by artificially creating a situation that forced the PDB drain strategy to execute.

So from a testing perspective I'm happy with things. I do want to review the changes made before approving this though. Will do that in the coming day or two.

**Comment by ravitri** [comment]
/hold
Checking merge conflict after recent changes merged to MUO

**Comment by mrbarge** [comment]
Just going to reiterate - I've given this a read-through now and it seems fine. Tested it successfully as noted earlier.
If anyone else wants to review, please leave the lgtm if/when satisfied.

**Pull request merged**
