### PR TITLE
Removed the unused spec objects - OSD-4780

### PR DESCRIPTION
**Pull request by himanshudogra**

### CODE REVIEW

**Comment by mrbarge** [comment]
Looks good to me, I have one request - could you please also update our documentation in the repository? The following docs reference the fields being removed and just need some small updates:

- `README.md`
- `docs/design.md`

**Comment by sedroche** [comment]
> Looks good to me, I have one request - could you please also update our documentation in the repository? The following docs reference the fields being removed and just need some small updates:
> 
> * `README.md`
> * `docs/design.md`

Probably were going to do this when doing the docs but also -> https://github.com/openshift/managed-upgrade-operator/blob/3372933de407a35d65df7fa402b19edb6ef41653/deploy/crds/upgrade.managed.openshift.io_v1alpha1_upgradeconfig_cr.yaml#L12

**Comment by himanshudogra** [comment]
I have raised another PR that will cover the removal of force and proceed from the design doc as well as crds. https://github.com/openshift/managed-upgrade-operator/pull/107

**Pull request merged**
